config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'
  root :to => 'pages#home'
  
  get 'session/new'
  resources :users
  
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  
  get '/team' => 'team#show'
  post '/team/remove' => 'team#remove'
  post '/team' => 'team#edit'

  
end

app/models/team.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: teams
#
#  id              :bigint(8)        not null, primary key
#  name            :string
#  conference      :string
#  division        :string
#  founded         :string
#  arena           :string
#  location        :string
#  colors          :string
#  general_manager :string
#  president       :string
#  headcoach       :string
#  championships   :string
#  team_url        :text
#  logo            :text
#

class Team < ActiveRecord::Base
  has_many :users
  has_many :news
  has_many :tweets
  has_many :players

  def validate_player(string)
    first_name = string.split(' ').first
    last_name = string[(string.index(' ') + 1)..string.length - 1]
    name = {
      first_n: first_name,
      last_n: last_name
    }
  end
end

app/controllers/team_controller.rb
# frozen_string_literal: true

class TeamController < ApplicationController
  before_action :check_for_login

  def show
    @team = Team.find_by id: session[:team_id]
    @followed_players = @current_user.players
  end

  def edit
    @team = Team.find_by id: session[:team_id]

    if params[:name].split(' ').length == 1 || params[:name].empty?
      return redirect_to team_path
    end

    name = Team.new
    name = name.validate_player params[:name] # returns a hash with first and last names stored

    player = Player.find_by last_name: name[:last_n], first_name: name[:first_n]

    return redirect_to team_path if player.nil?

    @current_user.players << player
    render :show
  end

  def remove
    player = @current_user.players.find_by id: params[:player_id]
    @current_user.players.delete(player)
    redirect_to(team_path)
  end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/team/show.html.erb
<%= content_tag :div, class: "temp_info", data: {temp: @current_user.players} do %>
<% end %>

<div class="container">

<div class="team-table">

  <div class="container column">
    <div class="team-heading">
      <%= image_tag @team.logo, :class => 'logo' %>
      <h1><%= @team.name %></h1>
    </div>

    <div class="player-search">
      <%= form_tag team_path do %>

      <%= label_tag :name, '' %>
      <%= text_field_tag :name, '', :placeholder => "SEARCH FOR A PLAYER EG. LEBRON JAMES", :class => 'player-search' %>

    <% end %>
  </div>

  <div class="following container">

    <% @current_user.players.each do |player| %>

      <span class="player"><%= player.name %>
        <span class="X"><%= link_to (image_tag "error.svg"), team_remove_path(:player_id => player.id), :action => team_remove_path, :method => 'post' %></span></span>

    <% end %>
  </div>

  <div class="hidden" id="chart">

    <canvas id="myChart"></canvas>

  </div>

</div>

<h3 class="stats">Team Stats</h3>
<div class="table-responsive container">
  <table id="team-players" class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th scope="col">First</th>
        <th scope="col">Last</th>
        <th scope="col">GP</th>
        <th scope="col">PPG</th>
        <th scope="col">TRB</th>
        <th scope="col">APG</th>
        <th scope="col">FG%</th>
        <th scope="col">3P%</th>
        <th scope="col">FT%</th>
        <th scope="col">eFG%</th>
        <th scope="col">PER</th>
        <th scope="col">WS</th>
      </tr>
    </thead>
    <tbody>
      <% @team.players.each do |stat| %>
        <% unless stat.games_played == "" || stat.games_played.nil? %>
          <tr>
            <td> <%= stat.first_name %></td>
            <td> <%= stat.last_name %></td>
            <td> <%= stat.games_played %></td>
            <td> <%= stat.ppg %></td>
            <td> <%= stat.trb %></td>
            <td> <%= stat.apg %></td>
            <td> <%= stat.fgperc %></td>
            <td> <%= stat.threepperc %></td>
            <td> <%= stat.ftperc %></td>
            <td> <%= stat.efgperc %></td>
            <td> <%= stat.per %></td>
            <td> <%= stat.ws %></td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>
</div>
</div>
<div class="container teams">
<div class="row">
  <div class="col-md-6">
    <div class="twitter-heading">
      <%= image_tag "twitter.svg", :class => 'icon1' %>
      <%= image_tag "hastag.svg", :class => 'icon2' %>
      <h4><%= @team.name.split.last %></h4>
    </div>
    <p>
      <% @team.tweets.last(15).each do |tweet| %>
        <%= tweet.embed.html_safe %>
      </p>
    <% end %>
  </div>

  <div class="col-md-6">
    <div class="news-heading">
      <%= image_tag "newspaper.svg", :class => 'icon3' %>
    </div>
    <% @team.news.last(15).each do |news| %>
      <div class="news-content">
        <h3><%= news.title %></h3>
        <% if news.image.present? %>
          <%= link_to (image_tag news.image, :class => 'news-image'), news.url, :target => "_blank" %>
        <% end %>
        <p>
          <%= news.content %>
          <%= link_to news.source, news.url, :target => "_blank" %>
        </p>
      </div>

    <% end %>     
  </div>

</div>
</div>