config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'
  root :to => 'pages#home'
  
  get 'session/new'
  resources :users
  
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  
  get '/team' => 'team#show'
  post '/team/remove' => 'team#remove'
  post '/team' => 'team#edit'

  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NBCrAy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    
    <ul class="nav nav-pills nav-fill navbar">
       <li class="nav-item">
      <%= link_to 'Home', root_path %>
       </li>
    <% if @current_user.present? %>
     <li class="nav-item">
    <%= link_to "Team Page", team_path %>
     </li>
      <li class="nav-item">
        <%= link_to "Sign Out", login_path, :method => 'delete' %>
          <%= link_to image_tag("gear.svg", :class => 'logo2' ), edit_user_path(@current_user.id) %>
               </li>
        <% else %>
            <li class="nav-item">
    <%= link_to 'Sign up', new_user_path %>
    </li>
    <li class="nav-item">
    <%= link_to 'Login', login_path %>
        </li>
    <% end %>
    </ul>  
    
  
    <%= yield %>
  </body>
</html>